apiVersion: v1
kind: Service
metadata:
  name: dsti-devops-service
  labels:
    app: dsti-devops-api
spec:
  type: NodePort
  selector:
    app: dsti-devops-api
  ports:
    - name: http
      port: 3000
      targetPort: 3000
      nodePort: 30080
